# References: https://cloud.google.com/build/docs/building/build-nodejs
# Used above reference and modify the code to include the step for creating docker image and pushing it to artifact registry
# and then deploying the workload to Google Kubernetes Cluster.

steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/kubernetes-cicd-pipeline/kubernetes-container-images/micro-service-app1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/kubernetes-cicd-pipeline/kubernetes-container-images/micro-service-app1']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=./kubernetes
    - --image=${_IMAGE_NAME}
    - --location=${_CLUSTER_LOCATION}
    - --cluster=${_CLUSTER_NAME}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/kubernetes-cicd-pipeline/kubernetes-container-images/micro-service-app1'
  _CLUSTER_LOCATION: 'us-central1-c'
  _CLUSTER_NAME: 'my-gke-cluster'
